### PR TITLE
Automatic builds

### LINKED ISSUE #16: Add GitHub Action for build after merge
I suggest we add a build job in the GitHub actions to build after merges to master branch to make sure that dist is always up to date with changes.

### PR DESCRIPTION
**Pull request by StelFoog**
Add workflow to perform builds automatically and some code cleanup

Resolves #16

### CODE REVIEW

**Review by Cactooz — APPROVED** [review]
Looks good.

Just two thoughts though:

- Maybe we should include a comment to the commit with the changes? Instead of only the commit name `[Build for changes made at] YYYY-MM-DD HH:mm:ss`.
- Also does the regex in `src/util/regex.ts` actually take the ISO dates? What if you send in 2023-03-02 for the 3rd of February?

**Comment by StelFoog** [comment]
@Cactooz 

- How do you mean? Any idea of what the comment would be?
- It would accept it, but it would also see it as the 2nd of March since that's the way the ISO standard works 😂 But I did notice an improvement that could be made

**Comment by Cactooz** [comment]
> How do you mean? Any idea of what the comment would be?

Like add the commit tag in the description or a link to that commit as the description sp you know what it built. For example, keep the current commit message with the date and add Built from commit: e4fdeb8` or something as a description.

**Comment by StelFoog** [comment]
> Like add the commit tag in the description or a link to that commit as the description sp you know what it built. For example, keep the current commit message with the date and add `Built from commit: e4fdeb8` or something as a description.
> @Cactooz 

Good idea. I'm not sure how easy it is to make it work but I'll look into it!

**Review by Cactooz — APPROVED** [review]
Looks good!

**Pull request merged**
